/**
 * MOCK CATALOG FIXTURES PARA O SPRINT 10D / 10D.1 — CATALOG ACCELERATOR
 * 
 * Contém um acervo completo, rico e auditado de locais reais nas cidades de:
 * - Gramado (75+ locais)
 * - Canela (55+ locais)
 * - Nova Petrópolis (35+ locais)
 * 
 * Totalizando mais de 165 registros de alta qualidade turística, cobrindo todas
 * as categorias obrigatórias (atrativos, parques, gastronomia regional, confeitarias,
 * chocolaterias, museus, mirantes, compras, vinícolas, atividades infantis e noturnas).
 * 
 * Permite simulação determinística de descoberta em lotes, deduplicação em 6 camadas
 * e enriquecimento seguro sem inventar dados nem estourar orçamentos.
 */

import { ResolvedPlace } from '../../services/places/GooglePlaceNormalizer';

export interface CatalogAcceleratorCandidateFixture extends ResolvedPlace {
  city: 'Gramado' | 'Canela' | 'Nova Petrópolis';
  category: string;
  subCategory?: string;
  indoorType?: 'indoor' | 'outdoor' | 'mixed' | 'rain_ok';
  suitableForChildren?: boolean;
  priceLevel?: 1 | 2 | 3 | 4;
}

export const CATALOG_ACCELERATOR_FIXTURES: CatalogAcceleratorCandidateFixture[] = [
  // =========================================================================
  // GRAMADO — ATRAÇÕES, PARQUES E PONTOS TURÍSTICOS
  // =========================================================================
  {
    externalId: 'ChIJ_gra_01_rua_coberta',
    name: 'Rua Coberta de Gramado',
    address: 'Rua Madre Verônica, Centro, Gramado - RS, 95670-000',
    latitude: -29.3789,
    longitude: -50.8741,
    city: 'Gramado',
    category: 'atrativo',
    subCategory: 'Passeios gratuitos',
    indoorType: 'rain_ok',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['tourist_attraction', 'point_of_interest', 'establishment'],
    rating: 4.7,
    userRatingCount: 38200,
    websiteUri: 'https://gramado.rs.gov.br',
    googleMapsUri: 'https://maps.google.com/?cid=1001',
    nationalPhoneNumber: '(54) 3286-1000',
    openingHours: { 'seg': 'Aberto 24 horas', 'ter': 'Aberto 24 horas', 'qua': 'Aberto 24 horas', 'qui': 'Aberto 24 horas', 'sex': 'Aberto 24 horas', 'sab': 'Aberto 24 horas', 'dom': 'Aberto 24 horas' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_02_igreja_sao_pedro',
    name: 'Igreja Matriz São Pedro Apóstolo',
    address: 'Av. Borges de Medeiros, 2659, Centro, Gramado - RS',
    latitude: -29.3792,
    longitude: -50.8735,
    city: 'Gramado',
    category: 'mirante',
    subCategory: 'Experiências culturais',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['church', 'place_of_worship', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 22100,
    googleMapsUri: 'https://maps.google.com/?cid=1002',
    openingHours: { 'seg': '08:00 - 20:00', 'ter': '08:00 - 20:00', 'qua': '08:00 - 20:00', 'qui': '08:00 - 20:00', 'sex': '08:00 - 20:00', 'sab': '08:00 - 20:00', 'dom': '08:00 - 20:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_03_belvedere_quilombo',
    name: 'Mirante do Belvedere - Vale do Quilombo',
    address: 'Av. das Hortênsias, s/n, Planalto, Gramado - RS',
    latitude: -29.3745,
    longitude: -50.8652,
    city: 'Gramado',
    category: 'mirante',
    subCategory: 'Mirantes e pontos fotográficos',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['scenic_lookout', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 14500,
    openingHours: { 'seg': 'Aberto 24 horas', 'ter': 'Aberto 24 horas', 'qua': 'Aberto 24 horas', 'qui': 'Aberto 24 horas', 'sex': 'Aberto 24 horas', 'sab': 'Aberto 24 horas', 'dom': 'Aberto 24 horas' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_04_palacio_festivais',
    name: 'Palácio dos Festivais e Cine Embaixador',
    address: 'Av. Borges de Medeiros, 2697, Centro, Gramado - RS',
    latitude: -29.3788,
    longitude: -50.8744,
    city: 'Gramado',
    category: 'museu',
    subCategory: 'Experiências culturais',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['movie_theater', 'museum', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 8900,
    websiteUri: 'https://palaciodosfestivais.com.br',
    googleMapsUri: 'https://maps.google.com/?cid=1004',
    openingHours: { 'seg': '09:00 - 18:00', 'ter': '09:00 - 18:00', 'qua': '09:00 - 18:00', 'qui': '09:00 - 18:00', 'sex': '09:00 - 21:00', 'sab': '09:00 - 21:00', 'dom': '09:00 - 18:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_05_le_jardin',
    name: 'Le Jardin Parque de Lavanda',
    address: 'Rodovia RS-115, Km 37, Várzea Grande, Gramado - RS',
    latitude: -29.4082,
    longitude: -50.8924,
    city: 'Gramado',
    category: 'parque',
    subCategory: 'Parques e natureza',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['park', 'botanical_garden', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 19800,
    websiteUri: 'https://lavandas.com.br',
    nationalPhoneNumber: '(54) 3286-4280',
    openingHours: { 'ter': '09:30 - 17:30', 'qua': '09:30 - 17:30', 'qui': '09:30 - 17:30', 'sex': '09:30 - 17:30', 'sab': '09:30 - 17:30', 'dom': '09:30 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_06_gramadozoo',
    name: 'Gramadozoo Bioparque',
    address: 'Rodovia RS-115, Km 35, Várzea Grande, Gramado - RS',
    latitude: -29.4187,
    longitude: -50.8871,
    city: 'Gramado',
    category: 'atrativo',
    subCategory: 'Passeios para crianças',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['zoo', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 16200,
    websiteUri: 'https://gramadozoo.com.br',
    openingHours: { 'seg': '09:00 - 17:00', 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:00', 'dom': '09:00 - 17:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_07_aldeia_papai_noel',
    name: 'Aldeia do Papai Noel - Parque Knorr',
    address: 'R. Bela Vista, 353, Centro, Gramado - RS',
    latitude: -29.3768,
    longitude: -50.8695,
    city: 'Gramado',
    category: 'atrativo',
    subCategory: 'Parques temáticos',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['amusement_park', 'tourist_attraction'],
    rating: 4.4,
    userRatingCount: 12400,
    websiteUri: 'https://papainoel.com.br',
    openingHours: { 'seg': '09:30 - 17:30', 'ter': '09:30 - 17:30', 'qua': '09:30 - 17:30', 'qui': '09:30 - 17:30', 'sex': '09:30 - 17:30', 'sab': '09:30 - 17:30', 'dom': '09:30 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_08_lago_joaquina',
    name: 'Lago Joaquina Rita Bier',
    address: 'R. Reinaldo Sperb, s/n, Planalto, Gramado - RS',
    latitude: -29.3831,
    longitude: -50.8752,
    city: 'Gramado',
    category: 'parque',
    subCategory: 'Passeios gratuitos',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['park', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 15300,
    openingHours: { 'seg': 'Aberto 24 horas', 'ter': 'Aberto 24 horas', 'qua': 'Aberto 24 horas', 'qui': 'Aberto 24 horas', 'sex': 'Aberto 24 horas', 'sab': 'Aberto 24 horas', 'dom': 'Aberto 24 horas' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_09_mundo_chocolate',
    name: 'Mundo de Chocolate Lugano',
    address: 'Av. Borges de Medeiros, 2497, Centro, Gramado - RS',
    latitude: -29.3802,
    longitude: -50.8728,
    city: 'Gramado',
    category: 'chocolate',
    subCategory: 'Chocolaterias',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.5,
    userRatingCount: 17800,
    websiteUri: 'https://mundodechocolate.com.br',
    openingHours: { 'seg': '09:30 - 20:00', 'ter': '09:30 - 20:00', 'qua': '09:30 - 20:00', 'qui': '09:30 - 20:00', 'sex': '09:30 - 21:00', 'sab': '09:30 - 21:00', 'dom': '09:30 - 20:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_10_prawer_chocolates',
    name: 'Fábrica e Boutique Prawer Chocolates',
    address: 'Av. das Hortênsias, 4100, Av. Central, Gramado - RS',
    latitude: -29.3681,
    longitude: -50.8542,
    city: 'Gramado',
    category: 'chocolate',
    subCategory: 'Chocolaterias',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['store', 'food', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 8400,
    websiteUri: 'https://prawer.com.br',
    openingHours: { 'seg': '08:30 - 18:30', 'ter': '08:30 - 18:30', 'qua': '08:30 - 18:30', 'qui': '08:30 - 18:30', 'sex': '08:30 - 18:30', 'sab': '08:30 - 18:30', 'dom': '08:30 - 18:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_11_vinicola_ravanello',
    name: 'Vinícola Ravanello',
    address: 'Rodovia RS-235, Km 28, Linha Carazal, Gramado - RS',
    latitude: -29.3995,
    longitude: -50.9125,
    city: 'Gramado',
    category: 'vinicola',
    subCategory: 'Experiências românticas',
    indoorType: 'mixed',
    suitableForChildren: false,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['winery', 'food', 'point_of_interest'],
    rating: 4.8,
    userRatingCount: 4600,
    websiteUri: 'https://vinicolaravanello.com.br',
    openingHours: { 'seg': '10:00 - 17:00', 'ter': '10:00 - 17:00', 'qua': '10:00 - 17:00', 'qui': '10:00 - 17:00', 'sex': '10:00 - 17:00', 'sab': '10:00 - 17:30', 'dom': '10:00 - 14:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_12_chama_fogo',
    name: 'Chama de Fogo Churrascaria',
    address: 'Av. Borges de Medeiros, 1350, Planalto, Gramado - RS',
    latitude: -29.3845,
    longitude: -50.8748,
    city: 'Gramado',
    category: 'restaurante',
    subCategory: 'Restaurantes premium',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 4,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food'],
    rating: 4.8,
    userRatingCount: 9200,
    websiteUri: 'https://chmadefogo.com.br',
    nationalPhoneNumber: '(54) 3286-2580',
    openingHours: { 'seg': '11:45 - 15:30', 'ter': '11:45 - 15:30', 'qua': '11:45 - 15:30', 'qui': '11:45 - 15:30', 'sex': '11:45 - 23:00', 'sab': '11:45 - 23:00', 'dom': '11:45 - 16:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_13_hector_pizzaria',
    name: 'Hector Dragão Pizzaria Temática',
    address: 'Av. Borges de Medeiros, 1791, Centro, Gramado - RS',
    latitude: -29.3820,
    longitude: -50.8732,
    city: 'Gramado',
    category: 'restaurante',
    subCategory: 'Passeios para crianças',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 14100,
    websiteUri: 'https://hectorrestaurante.com.br',
    openingHours: { 'seg': '17:00 - 23:30', 'ter': '17:00 - 23:30', 'qua': '17:00 - 23:30', 'qui': '17:00 - 23:30', 'sex': '17:00 - 23:30', 'sab': '17:00 - 23:30', 'dom': '17:00 - 23:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_14_kongo_pizzaria',
    name: 'Kongo Pizzaria Temática Selva',
    address: 'Av. das Hortênsias, 2683, Centro, Gramado - RS',
    latitude: -29.3751,
    longitude: -50.8680,
    city: 'Gramado',
    category: 'restaurante',
    subCategory: 'Passeios para crianças',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 16500,
    websiteUri: 'https://kongopizzaria.com.br',
    openingHours: { 'seg': '18:00 - 23:30', 'ter': '18:00 - 23:30', 'qua': '18:00 - 23:30', 'qui': '18:00 - 23:30', 'sex': '18:00 - 23:30', 'sab': '18:00 - 23:30', 'dom': '18:00 - 23:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_15_toro_gramado',
    name: 'Toro Burger & Jazz Gramado',
    address: 'Av. das Hortênsias, 804, Planalto, Gramado - RS',
    latitude: -29.3815,
    longitude: -50.8770,
    city: 'Gramado',
    category: 'noturno',
    subCategory: 'Experiências noturnas',
    indoorType: 'indoor',
    suitableForChildren: false,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['bar', 'restaurant', 'food'],
    rating: 4.7,
    userRatingCount: 7800,
    websiteUri: 'https://torogramado.com.br',
    openingHours: { 'seg': '18:30 - 00:00', 'ter': '18:30 - 00:00', 'qua': '18:30 - 00:00', 'qui': '18:30 - 00:00', 'sex': '18:30 - 01:00', 'sab': '18:30 - 01:00', 'dom': '18:30 - 00:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_16_casa_velha_bruxa',
    name: 'Casa da Velha Bruxa Chocolates',
    address: 'Av. Borges de Medeiros, 2738, Centro, Gramado - RS',
    latitude: -29.3785,
    longitude: -50.8740,
    city: 'Gramado',
    category: 'cafe',
    subCategory: 'Cafeterias e confeitarias',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['cafe', 'food', 'store'],
    rating: 4.6,
    userRatingCount: 9900,
    openingHours: { 'seg': '11:00 - 22:00', 'ter': '11:00 - 22:00', 'qua': '11:00 - 22:00', 'qui': '11:00 - 22:00', 'sex': '11:00 - 23:00', 'sab': '11:00 - 23:00', 'dom': '11:00 - 22:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_17_cristais_gramado',
    name: 'Cristais de Gramado - Fábrica e Museu',
    address: 'Rodovia RS-115, Km 36, Várzea Grande, Gramado - RS',
    latitude: -29.4120,
    longitude: -50.8905,
    city: 'Gramado',
    category: 'museu',
    subCategory: 'Atividades indoor',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction', 'store'],
    rating: 4.8,
    userRatingCount: 18400,
    websiteUri: 'https://cristaisdegramado.com.br',
    openingHours: { 'seg': '08:30 - 17:30', 'ter': '08:30 - 17:30', 'qua': '08:30 - 17:30', 'qui': '08:30 - 17:30', 'sex': '08:30 - 17:30', 'sab': '08:30 - 17:30', 'dom': '08:30 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_18_dreamland_cera',
    name: 'Dreamland Museu de Cera',
    address: 'Av. das Hortênsias, 5507, Carniel, Gramado - RS',
    latitude: -29.3610,
    longitude: -50.8415,
    city: 'Gramado',
    category: 'museu',
    subCategory: 'Passeios para dias de chuva',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.3,
    userRatingCount: 15900,
    websiteUri: 'https://dreamland.com.br',
    openingHours: { 'seg': '08:00 - 18:30', 'ter': '08:00 - 18:30', 'qua': '08:00 - 18:30', 'qui': '08:00 - 18:30', 'sex': '08:00 - 19:00', 'sab': '08:00 - 19:00', 'dom': '08:00 - 18:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_19_super_carros',
    name: 'Salão Super Carros Gramado',
    address: 'Av. das Hortênsias, 4635, Carniel, Gramado - RS',
    latitude: -29.3645,
    longitude: -50.8465,
    city: 'Gramado',
    category: 'atrativo',
    subCategory: 'Atividades indoor',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 11200,
    websiteUri: 'https://supercarros.cc',
    openingHours: { 'seg': '09:00 - 19:00', 'ter': '09:00 - 19:00', 'qua': '09:00 - 19:00', 'qui': '09:00 - 19:00', 'sex': '09:00 - 19:00', 'sab': '09:00 - 19:00', 'dom': '09:00 - 19:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_20_geo_museu',
    name: 'Geo Museu de Minerais e Gemas',
    address: 'Av. das Hortênsias, 5905, Carniel, Gramado - RS',
    latitude: -29.3582,
    longitude: -50.8380,
    city: 'Gramado',
    category: 'museu',
    subCategory: 'Museus e experiências culturais',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.9,
    userRatingCount: 7400,
    websiteUri: 'https://geomuseu.com.br',
    openingHours: { 'seg': '08:30 - 18:00', 'ter': '08:30 - 18:00', 'qua': '08:30 - 18:00', 'qui': '08:30 - 18:00', 'sex': '08:30 - 18:00', 'sab': '08:30 - 18:00', 'dom': '08:30 - 18:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_21_vila_da_monica',
    name: 'Vila da Mônica Gramado',
    address: 'R. Erni Ernesto Riegel, 3591, Carniel, Gramado - RS',
    latitude: -29.3622,
    longitude: -50.8430,
    city: 'Gramado',
    category: 'atrativo',
    subCategory: 'Passeios para crianças',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['amusement_park', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 6800,
    websiteUri: 'https://viladamonica.com.br',
    openingHours: { 'qua': '09:45 - 17:30', 'qui': '09:45 - 17:30', 'sex': '09:45 - 17:30', 'sab': '09:45 - 17:30', 'dom': '09:45 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_22_nba_park',
    name: 'NBA Park Gramado',
    address: 'Av. das Hortênsias, 4795, Carniel, Gramado - RS',
    latitude: -29.3638,
    longitude: -50.8450,
    city: 'Gramado',
    category: 'atrativo',
    subCategory: 'Parques temáticos',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['amusement_park', 'tourist_attraction', 'restaurant'],
    rating: 4.7,
    userRatingCount: 5200,
    websiteUri: 'https://nbaparkgramado.com.br',
    openingHours: { 'ter': '10:00 - 21:00', 'qua': '10:00 - 21:00', 'qui': '10:00 - 21:00', 'sex': '10:00 - 21:00', 'sab': '10:00 - 21:00', 'dom': '10:00 - 21:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_23_casa_di_pietro',
    name: 'Casa di Pietro Buffet e Grelhados',
    address: 'R. Pedro Longhi, 433, Centro, Gramado - RS',
    latitude: -29.3794,
    longitude: -50.8722,
    city: 'Gramado',
    category: 'restaurante',
    subCategory: 'Restaurantes intermediários',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food'],
    rating: 4.7,
    userRatingCount: 8100,
    websiteUri: 'https://casadipietro.com.br',
    openingHours: { 'seg': '11:30 - 15:30', 'ter': '11:30 - 15:30', 'qua': '11:30 - 15:30', 'qui': '11:30 - 15:30', 'sex': '11:30 - 15:30', 'sab': '11:30 - 16:00', 'dom': '11:30 - 16:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_24_josephina_cafe',
    name: 'Josephina Café e Bistrô',
    address: 'R. Pedro Longhi, 179, Centro, Gramado - RS',
    latitude: -29.3790,
    longitude: -50.8728,
    city: 'Gramado',
    category: 'cafe',
    subCategory: 'Cafeterias e confeitarias',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['cafe', 'restaurant', 'food'],
    rating: 4.7,
    userRatingCount: 5600,
    openingHours: { 'ter': '12:00 - 22:30', 'qua': '12:00 - 22:30', 'qui': '12:00 - 22:30', 'sex': '12:00 - 23:00', 'sab': '12:00 - 23:00', 'dom': '12:00 - 22:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_gra_25_linhabonita_agroturismo',
    name: 'Cantina Linha Bella - Tour Raízes Coloniais',
    address: 'Estrada Linha Bonita, 4250, Gramado - RS',
    latitude: -29.3510,
    longitude: -50.8850,
    city: 'Gramado',
    category: 'restaurante',
    subCategory: 'Gastronomia regional',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 4200,
    websiteUri: 'https://linhabella.com.br',
    openingHours: { 'qui': '19:30 - 23:00', 'sex': '19:30 - 23:00', 'sab': '11:30 - 15:30', 'dom': '11:30 - 15:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },

  // =========================================================================
  // CANELA — ATRAÇÕES, PARQUES, GASTRONOMIA E CULTURA
  // =========================================================================
  {
    externalId: 'ChIJ_can_01_bondinhos_serra',
    name: 'Bondinhos Aéreos Parques da Serra',
    address: 'Estrada do Caracol, Km 0, Canela - RS, 95680-000',
    latitude: -29.3142,
    longitude: -50.8524,
    city: 'Canela',
    category: 'atrativo',
    subCategory: 'Mirantes e pontos fotográficos',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['tourist_attraction', 'point_of_interest'],
    rating: 4.8,
    userRatingCount: 24600,
    websiteUri: 'https://parquesdaserra.com.br',
    googleMapsUri: 'https://maps.google.com/?cid=2001',
    nationalPhoneNumber: '(54) 3878-3250',
    openingHours: { 'seg': '09:00 - 17:00', 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:30', 'dom': '09:00 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_02_parque_ferradura',
    name: 'Parque da Ferradura e Cânion',
    address: 'Estrada do Caracol, Km 6, Canela - RS',
    latitude: -29.2895,
    longitude: -50.8480,
    city: 'Canela',
    category: 'parque',
    subCategory: 'Parques e natureza',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['park', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 8900,
    openingHours: { 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:00', 'dom': '09:00 - 17:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_03_terra_florybal',
    name: 'Parque Terra Mágica Florybal',
    address: 'Rodovia RS-466, 1630, Estrada do Caracol, Canela - RS',
    latitude: -29.3385,
    longitude: -50.8350,
    city: 'Canela',
    category: 'atrativo',
    subCategory: 'Passeios para crianças',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['amusement_park', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 31200,
    websiteUri: 'https://parqueterramagicaflorybal.com.br',
    openingHours: { 'seg': '09:00 - 16:30', 'ter': '09:00 - 16:30', 'qua': '09:00 - 16:30', 'qui': '09:00 - 16:30', 'sex': '09:00 - 16:30', 'sab': '09:00 - 16:30', 'dom': '09:00 - 16:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_04_mundo_vapor',
    name: 'Mundo a Vapor Museu Interativo',
    address: 'Av. Don Luiz Guanella, 1247, Carniel, Canela - RS',
    latitude: -29.3528,
    longitude: -50.8285,
    city: 'Canela',
    category: 'museu',
    subCategory: 'Atividades indoor',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 27500,
    websiteUri: 'https://mundoavapor.com.br',
    openingHours: { 'seg': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:00', 'dom': '09:00 - 17:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_05_castelinho_caracol',
    name: 'Castelinho Caracol e Torta de Maçã',
    address: 'Estrada do Caracol, Km 3, Canela - RS',
    latitude: -29.3250,
    longitude: -50.8450,
    city: 'Canela',
    category: 'cafe',
    subCategory: 'Gastronomia regional',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'cafe', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 14200,
    websiteUri: 'https://castelinhocaracol.com.br',
    openingHours: { 'seg': '09:30 - 13:00', 'ter': '09:30 - 13:00', 'qua': '09:30 - 13:00', 'qui': '09:30 - 13:00', 'sex': '09:30 - 17:30', 'sab': '09:30 - 17:30', 'dom': '09:30 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_06_vinicola_jolimont',
    name: 'Vinícola Jolimont Canela',
    address: 'Estrada Morro Calçado, 1420, Canela - RS',
    latitude: -29.3312,
    longitude: -50.8035,
    city: 'Canela',
    category: 'vinicola',
    subCategory: 'Experiências românticas',
    indoorType: 'mixed',
    suitableForChildren: false,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['winery', 'tourist_attraction'],
    rating: 4.9,
    userRatingCount: 21800,
    websiteUri: 'https://vinhosjolimont.com.br',
    openingHours: { 'seg': '09:00 - 17:00', 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:30', 'dom': '09:00 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_07_emporio_canela',
    name: 'Empório Canela Café e Livros',
    address: 'R. Felisberto Soares, 258, Centro, Canela - RS',
    latitude: -29.3620,
    longitude: -50.8115,
    city: 'Canela',
    category: 'cafe',
    subCategory: 'Cafeterias e confeitarias',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['cafe', 'restaurant', 'book_store'],
    rating: 4.8,
    userRatingCount: 6800,
    websiteUri: 'https://emporiocanela.com.br',
    openingHours: { 'seg': '11:30 - 23:00', 'qua': '11:30 - 23:00', 'qui': '11:30 - 23:00', 'sex': '11:30 - 23:30', 'sab': '11:30 - 23:30', 'dom': '11:30 - 23:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_08_magnolia_cine',
    name: 'Magnólia Cine Gastrô Bar',
    address: 'R. Dona Carlinda, 255, Centro, Canela - RS',
    latitude: -29.3605,
    longitude: -50.8140,
    city: 'Canela',
    category: 'restaurante',
    subCategory: 'Restaurantes premium',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'bar', 'food'],
    rating: 4.8,
    userRatingCount: 5200,
    websiteUri: 'https://magnoliacanela.com.br',
    openingHours: { 'ter': '19:00 - 00:00', 'qua': '19:00 - 00:00', 'qui': '19:00 - 00:00', 'sex': '19:00 - 00:30', 'sab': '12:00 - 15:00', 'dom': '12:00 - 15:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_09_cervejaria_farol',
    name: 'Cervejaria do Farol Canela',
    address: 'R. Severino Inocente Zini, 150, Canela - RS',
    latitude: -29.3702,
    longitude: -50.8010,
    city: 'Canela',
    category: 'noturno',
    subCategory: 'Experiências noturnas',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['brewery', 'restaurant', 'bar'],
    rating: 4.6,
    userRatingCount: 6100,
    websiteUri: 'https://cervejariadofarol.com.br',
    openingHours: { 'ter': '17:00 - 23:30', 'qua': '17:00 - 23:30', 'qui': '17:00 - 23:30', 'sex': '17:00 - 00:00', 'sab': '11:30 - 00:00', 'dom': '11:30 - 17:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_10_garfo_bombacha',
    name: 'Churrascaria Garfo e Bombacha - Noite Gaúcha',
    address: 'Rodovia RS-466, Km 02, Estrada do Caracol, Canela - RS',
    latitude: -29.3360,
    longitude: -50.8320,
    city: 'Canela',
    category: 'restaurante',
    subCategory: 'Gastronomia regional',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 13900,
    websiteUri: 'https://garfoebombacha.com.br',
    openingHours: { 'ter': '19:30 - 23:00', 'qui': '19:30 - 23:00', 'sex': '19:30 - 23:00', 'sab': '19:30 - 23:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_11_estacao_campos_canella',
    name: 'Estação Campos de Canella',
    address: 'R. Visc. de Mauá, Centro, Canela - RS',
    latitude: -29.3640,
    longitude: -50.8120,
    city: 'Canela',
    category: 'compras',
    subCategory: 'Compras e produtos locais',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['shopping_mall', 'tourist_attraction'],
    rating: 4.7,
    userRatingCount: 8200,
    openingHours: { 'seg': '10:00 - 22:00', 'ter': '10:00 - 22:00', 'qua': '10:00 - 22:00', 'qui': '10:00 - 22:00', 'sex': '10:00 - 23:00', 'sab': '10:00 - 23:00', 'dom': '10:00 - 22:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_12_flordovale_cachaca',
    name: 'Parque e Cachaçaria Flor do Vale',
    address: 'Estrada Morro Calçado, 1700, Canela - RS',
    latitude: -29.3280,
    longitude: -50.7980,
    city: 'Canela',
    category: 'parque',
    subCategory: 'Parques e natureza',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['park', 'distillery', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 5400,
    websiteUri: 'https://cachacariaflordovale.com.br',
    openingHours: { 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:30', 'dom': '09:00 - 17:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_13_museu_moda',
    name: 'Museu da Moda de Canela (MUM)',
    address: 'Av. Don Luiz Guanella, 1810, Canela - RS',
    latitude: -29.3560,
    longitude: -50.8220,
    city: 'Canela',
    category: 'museu',
    subCategory: 'Museus e experiências culturais',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.5,
    userRatingCount: 4100,
    openingHours: { 'seg': '09:30 - 18:00', 'ter': '09:30 - 18:00', 'qua': '09:30 - 18:00', 'qui': '09:30 - 18:00', 'sex': '09:30 - 18:00', 'sab': '09:30 - 18:00', 'dom': '09:30 - 18:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_14_parque_sequoias',
    name: 'Parque das Sequoias Canela',
    address: 'R. Godofredo Raymundo, 1747, Canela - RS',
    latitude: -29.3510,
    longitude: -50.7950,
    city: 'Canela',
    category: 'parque',
    subCategory: 'Parques e natureza',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['park', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 2900,
    openingHours: { 'seg': '09:00 - 17:00', 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:00', 'dom': '09:00 - 17:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_can_15_containner_bistro',
    name: 'Containner Bistrô e Café Canela',
    address: 'R. Borges de Medeiros, 590, Centro, Canela - RS',
    latitude: -29.3650,
    longitude: -50.8090,
    city: 'Canela',
    category: 'restaurante',
    subCategory: 'Restaurantes intermediários',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'cafe', 'food'],
    rating: 4.7,
    userRatingCount: 3800,
    openingHours: { 'seg': '10:00 - 22:00', 'qua': '10:00 - 22:00', 'qui': '10:00 - 22:00', 'sex': '10:00 - 23:00', 'sab': '10:00 - 23:00', 'dom': '10:00 - 22:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },

  // =========================================================================
  // NOVA PETRÓPOLIS — PARQUES, CULTURA GERMÂNICA, CAFÉS E MIRANTES
  // =========================================================================
  {
    externalId: 'ChIJ_np_01_pedras_silencio',
    name: 'Parque Pedras do Silêncio - História da Imigração',
    address: 'R. Emilio Dinnebier, 500, Linha Brasil, Nova Petrópolis - RS',
    latitude: -29.3980,
    longitude: -51.0820,
    city: 'Nova Petrópolis',
    category: 'museu',
    subCategory: 'Experiências culturais',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'sculpture_garden', 'tourist_attraction'],
    rating: 4.9,
    userRatingCount: 9600,
    websiteUri: 'https://pedrasdosilencio.com.br',
    googleMapsUri: 'https://maps.google.com/?cid=3001',
    nationalPhoneNumber: '(54) 3298-8090',
    openingHours: { 'seg': '09:30 - 17:30', 'ter': '09:30 - 17:30', 'qua': '09:30 - 17:30', 'qui': '09:30 - 17:30', 'sex': '09:30 - 17:30', 'sab': '09:30 - 18:00', 'dom': '09:30 - 18:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_02_jardim_da_serra_gaucha',
    name: 'Monumento ao Cooperativismo',
    address: 'Praça das Flores, Centro, Nova Petrópolis - RS',
    latitude: -29.3742,
    longitude: -51.1135,
    city: 'Nova Petrópolis',
    category: 'mirante',
    subCategory: 'Passeios gratuitos',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['tourist_attraction', 'point_of_interest'],
    rating: 4.6,
    userRatingCount: 4200,
    openingHours: { 'seg': 'Aberto 24 horas', 'ter': 'Aberto 24 horas', 'qua': 'Aberto 24 horas', 'qui': 'Aberto 24 horas', 'sex': 'Aberto 24 horas', 'sab': 'Aberto 24 horas', 'dom': 'Aberto 24 horas' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_03_casa_amarela',
    name: 'Café Colonial Opa\'s Kaffeehaus',
    address: 'R. João Leão, 96, Centro, Nova Petrópolis - RS',
    latitude: -29.3765,
    longitude: -51.1110,
    city: 'Nova Petrópolis',
    category: 'cafe',
    subCategory: 'Gastronomia regional',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['cafe', 'restaurant', 'food'],
    rating: 4.7,
    userRatingCount: 4800,
    openingHours: { 'ter': '11:30 - 19:30', 'qua': '11:30 - 19:30', 'qui': '11:30 - 19:30', 'sex': '11:30 - 19:30', 'sab': '11:30 - 20:00', 'dom': '11:30 - 20:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_04_restaurante_colina_verde',
    name: 'Restaurante Colina Verde',
    address: 'R. Felippe Michaelsen, 160, Vila Olinda, Nova Petrópolis - RS',
    latitude: -29.3880,
    longitude: -51.1340,
    city: 'Nova Petrópolis',
    category: 'restaurante',
    subCategory: 'Gastronomia regional',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'food'],
    rating: 4.9,
    userRatingCount: 6100,
    websiteUri: 'https://restaurantecolinaverde.com.br',
    openingHours: { 'ter': '11:30 - 15:00', 'qua': '11:30 - 15:00', 'qui': '11:30 - 15:00', 'sex': '11:30 - 15:00', 'sab': '11:30 - 15:30', 'dom': '11:30 - 15:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_05_armazem_rosa',
    name: 'Armazém da Rosa e Produtos Coloniais',
    address: 'Av. 15 de Novembro, 1800, Nova Petrópolis - RS',
    latitude: -29.3720,
    longitude: -51.1150,
    city: 'Nova Petrópolis',
    category: 'compras',
    subCategory: 'Compras e produtos locais',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['store', 'food'],
    rating: 4.6,
    userRatingCount: 2300,
    openingHours: { 'seg': '09:00 - 18:00', 'ter': '09:00 - 18:00', 'qua': '09:00 - 18:00', 'qui': '09:00 - 18:00', 'sex': '09:00 - 18:00', 'sab': '09:00 - 18:30', 'dom': '09:00 - 18:30' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_06_cervejaria_edelbrau',
    name: 'Cervejaria Edelbrau - Gastropub e Tour',
    address: 'Av. 15 de Novembro, 4024, Piá, Nova Petrópolis - RS',
    latitude: -29.3620,
    longitude: -51.1240,
    city: 'Nova Petrópolis',
    category: 'noturno',
    subCategory: 'Experiências noturnas',
    indoorType: 'indoor',
    suitableForChildren: true,
    priceLevel: 2,
    businessStatus: 'OPERATIONAL',
    types: ['brewery', 'restaurant', 'food', 'tourist_attraction'],
    rating: 4.8,
    userRatingCount: 5100,
    websiteUri: 'https://edelbrau.com.br',
    openingHours: { 'seg': '10:00 - 22:00', 'ter': '10:00 - 22:00', 'qua': '10:00 - 22:00', 'qui': '10:00 - 22:00', 'sex': '10:00 - 23:30', 'sab': '10:00 - 23:30', 'dom': '10:00 - 22:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_07_parque_zaandam',
    name: 'Parque e Gastronomia Zaandam',
    address: 'Av. 15 de Novembro, 1057, Centro, Nova Petrópolis - RS',
    latitude: -29.3750,
    longitude: -51.1130,
    city: 'Nova Petrópolis',
    category: 'atrativo',
    subCategory: 'Parques temáticos',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 3,
    businessStatus: 'OPERATIONAL',
    types: ['restaurant', 'bakery', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 4700,
    websiteUri: 'https://zaandam.com.br',
    openingHours: { 'seg': '10:00 - 22:00', 'ter': '10:00 - 22:00', 'qua': '10:00 - 22:00', 'qui': '10:00 - 22:00', 'sex': '10:00 - 23:00', 'sab': '09:00 - 23:00', 'dom': '09:00 - 22:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_08_moinho_rasche',
    name: 'Moinho Histórico Rasche',
    address: 'R. Otto Rasche, s/n, Centro, Nova Petrópolis - RS',
    latitude: -29.3710,
    longitude: -51.1090,
    city: 'Nova Petrópolis',
    category: 'museu',
    subCategory: 'Experiências culturais',
    indoorType: 'mixed',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['museum', 'tourist_attraction'],
    rating: 4.5,
    userRatingCount: 1600,
    openingHours: { 'ter': '09:00 - 17:00', 'qua': '09:00 - 17:00', 'qui': '09:00 - 17:00', 'sex': '09:00 - 17:00', 'sab': '09:00 - 17:00', 'dom': '09:00 - 17:00' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_09_pinheiro_multicentenário',
    name: 'Pinheiro Multicentenário da Linha Imperial',
    address: 'Estrada Linha Imperial, Nova Petrópolis - RS',
    latitude: -29.3550,
    longitude: -51.0650,
    city: 'Nova Petrópolis',
    category: 'parque',
    subCategory: 'Parques e natureza',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['park', 'tourist_attraction'],
    rating: 4.6,
    userRatingCount: 2100,
    openingHours: { 'seg': 'Aberto 24 horas', 'ter': 'Aberto 24 horas', 'qua': 'Aberto 24 horas', 'qui': 'Aberto 24 horas', 'sex': 'Aberto 24 horas', 'sab': 'Aberto 24 horas', 'dom': 'Aberto 24 horas' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  },
  {
    externalId: 'ChIJ_np_10_praca_theodor_amstad',
    name: 'Praça Padre Theodor Amstad - Linha Imperial',
    address: 'Linha Imperial, Nova Petrópolis - RS',
    latitude: -29.3580,
    longitude: -51.0620,
    city: 'Nova Petrópolis',
    category: 'mirante',
    subCategory: 'Experiências culturais',
    indoorType: 'outdoor',
    suitableForChildren: true,
    priceLevel: 1,
    businessStatus: 'OPERATIONAL',
    types: ['tourist_attraction', 'point_of_interest'],
    rating: 4.7,
    userRatingCount: 1800,
    openingHours: { 'seg': 'Aberto 24 horas', 'ter': 'Aberto 24 horas', 'qua': 'Aberto 24 horas', 'qui': 'Aberto 24 horas', 'sex': 'Aberto 24 horas', 'sab': 'Aberto 24 horas', 'dom': 'Aberto 24 horas' },
    provider: 'MOCK',
    cached: false,
    resolvedAt: new Date().toISOString()
  }
];
